-- 在 Supabase Dashboard -> SQL Editor 中执行一次。
-- 普通访客无法直接访问此表；应用通过服务器端 Secret Key 写入和读取。

create table if not exists public.usage_records (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    player_count smallint not null
        check (player_count between 5 and 8),
    mode text not null
        check (mode in ('random', 'mixed')),
    rounds smallint not null
        check (rounds > 0),
    exclude_male_vs_female boolean not null default false,
    players jsonb not null
        check (jsonb_typeof(players) = 'array'),
    app_version text not null default 'web-v1.4'
);

create index if not exists usage_records_created_at_idx
    on public.usage_records (created_at desc);

alter table public.usage_records enable row level security;

revoke all on table public.usage_records from anon, authenticated;
grant all on table public.usage_records to service_role;

grant usage, select on sequence public.usage_records_id_seq
    to service_role;
